# yamllint disable rule:line-length
---
image: node:latest

before_script:
  - yarn install --pure-lockfile

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  AWS_DEFAULT_REGION: eu-west-2

build:
  stage: build
  script:
    - yarn run build
  artifacts:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build/
    expire_in: 1 week

deploy:
  stage: deploy
  environment:
    name: CloudFront
    url: https://osborn.io
  only:
    - master
  script:
    - yarn run deploy
...
