[build]
  command = "yarn build"
  publish = "build/"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; style-src https://www.w3.org; upgrade-insecure-requests; report-uri https://nosborn.report-uri.com/r/d/csp/enforce"
    Expect-CT = "report-uri=\"https://nosborn.report-uri.com/r/d/ct/enforce\", enforce, max-age=86400"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "http://www-osborn-io.netlify.com/*"
  to = "http://www.osborn.io/:splat"
  force = true
