---
name: Pull Request

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
