---
name: Push

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md

env:
  CI: true

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: deploy to S3
        run: |
          yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
